# Getting Things Done in Python

## Generating Data

### Vectors

In [1]:
# import standard packages
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.mlab import frange

In [2]:
# Note that the last value is NOT included!
x = np.arange(1,5,0.5)
x

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [3]:
y = np.linspace(0,1,11)
y

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [4]:
# "frange" includes the last value
z = frange(1,3)
z

array([ 1.,  2.,  3.])

### Matrices and Vectors

In [5]:
zero_vector = np.zeros(3)
zero_vector

array([ 0.,  0.,  0.])

In [6]:
zero_matrix = np.zeros( (3,3))
zero_matrix

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

The command *np.ones* offer similar functionality as *zeros*.
*np.random.randn* in contrast can use more than one input argument:

In [7]:
np.random.randn(3,2)

array([[-0.60003847,  0.15409103],
       [ 0.28522034, -1.89274418],
       [ 1.57178316, -0.69348745]])

####  Row- and column-vectors

In [8]:
row_vector = np.array([1,2,3])
row_vector

array([1, 2, 3])

In [9]:
row_vector2 = np.r_[3,4,5]
row_vector2

array([3, 4, 5])

In [10]:
col_vector = np.c_[[4,5,6]]
col_vector

array([[4],
       [5],
       [6]])

#### Rotation of a vector

In [11]:
# Rotation by 30 deg
alpha = np.deg2rad(30)
RotMat = np.array([[np.cos(alpha), -np.sin(alpha)],
                  [np.sin(alpha), np.cos(alpha)]])
vec = np.r_[1,0]
vec_rotated = RotMat.dot(vec)
vec_rotated

array([ 0.8660254,  0.5      ])

#### "Broadcasting"

In [12]:
data = np.arange(15).reshape((5,3))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
# overall mean
np.mean(data)

7.0

In [14]:
# mean over all rows
np.mean(data, axis=0)

array([ 6.,  7.,  8.])

In [15]:
# "Broadcasting": if the second index matches, the
# operation is applied to each row:
data - np.mean(data, axis=0)

array([[-6., -6., -6.],
       [-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.],
       [ 6.,  6.,  6.]])

In [16]:
# This only works on the last index!
data - np.mean(data, axis=1)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 